// <auto-generated />
using System;
using BlogSite.DataAccess.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlogSite.DataAccess.Migrations
{
    [DbContext(typeof(BaseDbContext))]
    partial class BaseDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BlogSite.Models.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CategoryId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreateTime");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CategoryName");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("UpdateTime");

                    b.HasKey("Id");

                    b.ToTable("Categories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2022, 5, 1, 14, 30, 0, 0, DateTimeKind.Unspecified),
                            Name = "Csharp"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2023, 1, 15, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Javascript"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2021, 12, 25, 18, 45, 0, 0, DateTimeKind.Unspecified),
                            Name = "React"
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2024, 7, 10, 23, 59, 59, 0, DateTimeKind.Unspecified),
                            Name = "Bootstrap"
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2020, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Html"
                        });
                });

            modelBuilder.Entity("BlogSite.Models.Entities.Comment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("CommentId");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreateTime");

                    b.Property<Guid>("PostId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Post_Id");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Text");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("UpdateTime");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("User_Id");

                    b.HasKey("Id");

                    b.HasIndex("PostId");

                    b.HasIndex("UserId");

                    b.ToTable("Comments", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("e329227c-ee67-409a-b64e-46a7be585e89"),
                            CreatedDate = new DateTime(2024, 10, 17, 11, 15, 0, 0, DateTimeKind.Unspecified),
                            PostId = new Guid("702fe6ef-9dba-4219-b8a5-3a710e128e39"),
                            Text = "Çok güzel bir yazı.",
                            UserId = 2L
                        },
                        new
                        {
                            Id = new Guid("58124570-a62a-4297-a6ea-c6a5a79c931a"),
                            CreatedDate = new DateTime(2024, 10, 19, 16, 45, 0, 0, DateTimeKind.Unspecified),
                            PostId = new Guid("a0340a0c-a702-4b19-b808-fce464311f43"),
                            Text = "Yazıyı beğenmedim.",
                            UserId = 3L
                        });
                });

            modelBuilder.Entity("BlogSite.Models.Entities.Post", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("PostId");

                    b.Property<long>("AuthorId")
                        .HasColumnType("bigint")
                        .HasColumnName("Author_Id");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int")
                        .HasColumnName("Category_Id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Content");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreateTime");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Title");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("UpdateTime");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Posts", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("702fe6ef-9dba-4219-b8a5-3a710e128e39"),
                            AuthorId = 1L,
                            CategoryId = 1,
                            Content = "C# is a versatile and powerful programming language that has become a cornerstone of modern software development. Developed by Microsoft, C# is known for its robustness, simplicity, and efficiency, making it a popular choice for building a wide range of applications, from web and mobile apps to desktop software and games. One of the key strengths of C# lies in its strong typing and object-oriented nature, which promotes clear and maintainable code. With features like Language Integrated Query (LINQ), async/await for asynchronous programming, and the powerful .NET ecosystem, C# enables developers to write high-performance, scalable applications.",
                            CreatedDate = new DateTime(2024, 10, 20, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Exploring the Power of C# in Modern Software Development"
                        },
                        new
                        {
                            Id = new Guid("94ebf6ec-9264-4c8e-b27f-428c1dfa3867"),
                            AuthorId = 5L,
                            CategoryId = 2,
                            Content = "JavaScript is the cornerstone of modern web development, infusing interactivity and dynamism into web pages. From simple scripts that handle form validations to complex frameworks and libraries like React and Angular, JavaScript powers the responsive and engaging experiences users expect from contemporary websites. It allows developers to create real-time updates, handle asynchronous operations, and manipulate the DOM, making web applications more user-friendly and efficient.",
                            CreatedDate = new DateTime(2024, 10, 12, 19, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "JavaScript: The Dynamic Heart of Web Development"
                        },
                        new
                        {
                            Id = new Guid("53e2d227-bff2-4588-9e89-541cccfb9e02"),
                            AuthorId = 3L,
                            CategoryId = 3,
                            Content = "React is a powerful library for building user interfaces, developed by Facebook. It’s particularly well-suited for creating dynamic and interactive web applications. With its component-based architecture, React allows developers to break down complex UIs into manageable, reusable pieces. This modular approach enhances maintainability and scalability. React’s virtual DOM ensures efficient updates and rendering, boosting performance. By embracing a declarative style, React makes it easier to reason about the state of your application and predict its behavior.",
                            CreatedDate = new DateTime(2024, 10, 14, 8, 30, 0, 0, DateTimeKind.Unspecified),
                            Title = "React: Building Interactive User Interfaces"
                        },
                        new
                        {
                            Id = new Guid("284a37ec-2675-4fa0-bca5-becc691abd63"),
                            AuthorId = 4L,
                            CategoryId = 5,
                            Content = "HTML, or HyperText Markup Language, is the fundamental building block of the web. It provides the structure and semantics for web content, defining elements like headings, paragraphs, links, and images. HTML is crucial for ensuring that web pages are accessible and searchable. It works seamlessly with CSS and JavaScript to create rich, interactive web experiences. Understanding HTML is essential for any web developer, as it forms the basis upon which all web technologies are built.",
                            CreatedDate = new DateTime(2024, 10, 17, 14, 45, 0, 0, DateTimeKind.Unspecified),
                            Title = "HTML: The Foundation of the Web"
                        },
                        new
                        {
                            Id = new Guid("a0340a0c-a702-4b19-b808-fce464311f43"),
                            AuthorId = 2L,
                            CategoryId = 4,
                            Content = "Bootstrap is a powerful front-end framework that simplifies the development of responsive and mobile-first websites. With its grid system, pre-styled components, and utility classes, Bootstrap makes it easy to create layouts that adapt to different screen sizes and devices. It includes a variety of customizable UI elements like buttons, modals, and navigation bars, allowing developers to build polished and professional-looking websites quickly. Bootstrap’s extensive documentation and community support make it a go-to choice for both beginners and experienced developers.",
                            CreatedDate = new DateTime(2024, 10, 19, 11, 15, 0, 0, DateTimeKind.Unspecified),
                            Title = "Bootstrap: Streamlining Responsive Web Design"
                        });
                });

            modelBuilder.Entity("BlogSite.Models.Entities.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("UserId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("FirstName");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("LastName");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Password");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Username");

                    b.HasKey("Id");

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedDate = new DateTime(2024, 10, 5, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "myusuf@gmail.com",
                            FirstName = "Muhammed Yusuf",
                            LastName = "Aydın",
                            Password = "12345!61",
                            Username = "myusuf"
                        },
                        new
                        {
                            Id = 2L,
                            CreatedDate = new DateTime(2024, 10, 10, 17, 15, 0, 0, DateTimeKind.Unspecified),
                            Email = "eyilmaz@gmail.com",
                            FirstName = "Esra",
                            LastName = "Yılmaz",
                            Password = "esra123!",
                            Username = "esraylmz"
                        },
                        new
                        {
                            Id = 3L,
                            CreatedDate = new DateTime(2024, 10, 15, 9, 45, 0, 0, DateTimeKind.Unspecified),
                            Email = "berk@gmail.com",
                            FirstName = "Berk",
                            LastName = "Aydoğdu",
                            Password = "berk456!",
                            Username = "berkayd"
                        },
                        new
                        {
                            Id = 4L,
                            CreatedDate = new DateTime(2024, 10, 18, 15, 30, 0, 0, DateTimeKind.Unspecified),
                            Email = "öznur@gmail.com",
                            FirstName = "Öznur",
                            LastName = "Altın",
                            Password = "öznur789!",
                            Username = "oznuraltn"
                        },
                        new
                        {
                            Id = 5L,
                            CreatedDate = new DateTime(2024, 10, 20, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "fatih@gmail.com",
                            FirstName = "Fatih",
                            LastName = "Şan",
                            Password = "fatih246!",
                            Username = "fatihsn"
                        });
                });

            modelBuilder.Entity("BlogSite.Models.Entities.Comment", b =>
                {
                    b.HasOne("BlogSite.Models.Entities.Post", "Post")
                        .WithMany("Comments")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("BlogSite.Models.Entities.User", "User")
                        .WithMany("Comments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BlogSite.Models.Entities.Post", b =>
                {
                    b.HasOne("BlogSite.Models.Entities.User", "Author")
                        .WithMany("Posts")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BlogSite.Models.Entities.Category", "Category")
                        .WithMany("Posts")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("BlogSite.Models.Entities.Category", b =>
                {
                    b.Navigation("Posts");
                });

            modelBuilder.Entity("BlogSite.Models.Entities.Post", b =>
                {
                    b.Navigation("Comments");
                });

            modelBuilder.Entity("BlogSite.Models.Entities.User", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Posts");
                });
#pragma warning restore 612, 618
        }
    }
}
